image:
  file: .gitpod.Dockerfile

# Timezone Tokyo
tasks:
  - init: npm install
  - command: export TZ="Asia/Tokyo"

# Postgresql extension
vscode:
  extensions:
    - ckolkman.vscode-postgres@1.1.17:804d27cd5e9ff60a8c46a387413e9cbf
