image:
  file: .gitpod.Dockerfile

# Timezone Tokyo
tasks:
  - init: npm install
      &&  npx sequelize db:create
      &&  npx sequelize db:migrate
      &&  npx sequelize db:seed:all
    command: export TZ="Asia/Tokyo"

# Postgresql extension
vscode:
  extensions:
    - ckolkman.vscode-postgres@1.1.17:804d27cd5e9ff60a8c46a387413e9cbf
